### ISSUE TITLE
关于ps设置显示该图像距离附近图像的距离问题

### ISSUE THREAD

**Issue by ldd-bit** [lipengzhou/toutiao-mobile#10]
1. 如何把ps中设置的像老师那样点一下就可以出来当前被点击的图像距离别的图像的间距`

**Comment by lipengzhou** [comment]
照着我写的这篇教程做：https://gist.github.com/lipengzhou/0e8a9e4a8f193fa0509ff54baf4b66ba

**Comment by ldd-bit** [comment]
老师,我想要这样的效果: 
![image](https://user-images.githubusercontent.com/62420075/81494542-35b90600-92dc-11ea-9b03-a655d7745de5.png)

**Comment by lipengzhou** [comment]
选中需要测量的图层，按住 Ctrl 不要丢，移动鼠标指针自动就出来了。
如果还是没有，那应该是 Photoshop 版本比较低，升级就好了。
我的 Photoshop 版本是 2020。

**Comment by ldd-bit** [comment]
好的,感谢老师,已解决
