### ISSUE TITLE
表单验证不通过,发送登录请求

### ISSUE THREAD

**Issue by cheng-long123** [lipengzhou/toutiao-mobile#11]
![image](https://user-images.githubusercontent.com/62420201/81491127-e1525e00-92bc-11ea-9498-5aade928ea24.png)

**Comment by lipengzhou** [comment]
请确保下面几个事项：

- 将登陆按钮放到表单中
- 不要给登录按钮注册任何事件
- 给 form 组件注册 submit 事件处理登录

![image](https://user-images.githubusercontent.com/23165266/81491328-fda3ca00-92bf-11ea-9fca-61fac84cbf46.png)

如果还不行，请参考这个内容进行处理：https://youzan.github.io/vant/#/zh-CN/form#chang-jian-wen-ti

**Comment by cheng-long123** [comment]
感谢  解决了
