### ISSUE TITLE
echarts label不支持标签显示

### ISSUE THREAD

**Issue by li-erjun** [lipengzhou/toutiao-mobile#12]
![image](https://user-images.githubusercontent.com/64782193/81501508-52b8fd80-930b-11ea-8617-880217e1fe73.png)

**Comment by lipengzhou** [comment]
不能直接渲染标签，具体请参考这里：https://echarts.apache.org/zh/tutorial.html#%E5%AF%8C%E6%96%87%E6%9C%AC%E6%A0%87%E7%AD%BE
