### ISSUE TITLE
使用自己手机号码接收验证码登录,报错400

### ISSUE THREAD

**Issue by Zeng5475** [lipengzhou/toutiao-mobile#13]
### 该问题是怎么引起的?
使用自己手机号接受到的验证码,点击登录,报错400,  但是换13111111111,加万能验证码可以登录成功.

### 错误详情
![QQ截图20200510224405](https://user-images.githubusercontent.com/45525582/81502343-f5737b00-930f-11ea-8d72-8f98221277f8.png)

### 代码截图

![数据](https://user-images.githubusercontent.com/45525582/81502427-82b6cf80-9310-11ea-8976-061d500192c4.png)

![接口](https://user-images.githubusercontent.com/45525582/81502431-89dddd80-9310-11ea-9d37-37b73c57cb18.png)

![登录](https://user-images.githubusercontent.com/45525582/81502435-8d716480-9310-11ea-9b4e-72ed31b8a5f8.png)

**Comment by Zeng5475** [comment]
user中数据中不是字符串

**Comment by lipengzhou** [comment]
数据类型必须是字符串哦。

![image](https://user-images.githubusercontent.com/23165266/81502645-b47c6600-9311-11ea-90e7-16d74381d422.png)

> 这是接口文档中的说明

![image](https://user-images.githubusercontent.com/23165266/81502629-9d3d7880-9311-11ea-9edb-0f8c431ebbb4.png)

> 这是我的代码，字符串类型

**Comment by Zeng5475** [comment]
刚提交上去,  发现出那里的问题了, 已经解决了.
