### ISSUE TITLE
谷歌浏览器不支持12px以下的字体,如何修改

### ISSUE THREAD

**Issue by ldd-bit** [lipengzhou/toutiao-mobile#15]
> 我发现10px和12px的字体大小一样,但是样式已经修改了,应该是谷歌浏览器不支持,请问该如何修改

**Comment by ldd-bit** [comment]
问题已解决,辛苦了

**Comment by lipengzhou** [comment]
我们做的是手机网站，谷歌浏览器只是一个查看和调试的工具，谷歌浏览器中的表现不会和手机完全一样。具体最后以手机上的为准，不支持也不需要支持。
