### ISSUE TITLE
小智同学下面的边距调不出来

### ISSUE THREAD

**Issue by qianshou99** [lipengzhou/toutiao-mobile#17]
![image](https://user-images.githubusercontent.com/62420203/81674790-591cb600-9480-11ea-9649-ba21dae08ee4.png)
![image](https://user-images.githubusercontent.com/62420203/81674816-62a61e00-9480-11ea-859a-e9c378cf6752.png)

**Comment by lipengzhou** [comment]
你要给 body 要设置背景底色的。

**Comment by qianshou99** [comment]
![image](https://user-images.githubusercontent.com/62420203/81675124-e233ed00-9480-11ea-910e-d49eeeb0888e.png)
我设置了,上面出来了,下面的没有

**Comment by lipengzhou** [comment]
把你的代码推到线上，仓库地址发我。

**Comment by qianshou99** [comment]
https://gitee.com/qianshou99/toutiao-m

**Comment by lipengzhou** [comment]
不能给它套 `van-cell-group` 。

![image](https://user-images.githubusercontent.com/23165266/81683357-a69d2100-9488-11ea-8911-18a5f656a942.png)

**Comment by qianshou99** [comment]
已解决
