### ISSUE TITLE
报错401

### ISSUE THREAD

**Issue by mojina8** [lipengzhou/toutiao-mobile#20]
### 概述
在我的页面中获取不到页面信息，进入 my 页面控制台报401错误
### 报错信息
![image](https://user-images.githubusercontent.com/52235130/81757116-50fc5f00-94f0-11ea-86d6-e46f043a5122.png)

### 你的代码

最好是你的仓库地址并且确认你已把代码更新到线上。

**Comment by lipengzhou** [comment]
你没有登录就获取当前登录用户信息，肯定就报错 401，解决办法就是在获取当前登录用户数据的时候加个判断即可：

```js
created () {
  if (this.user) {
    this.loadCurrentUser()
  }
},
```

**Comment by mojina8** [comment]
![image](https://user-images.githubusercontent.com/52235130/81760101-f5829f00-94f8-11ea-9e39-4de06ad40a27.png)
我有这个，但是还是报401

**Comment by lipengzhou** [comment]
![image](https://user-images.githubusercontent.com/23165266/81760253-53af8200-94f9-11ea-9150-cc40ba61e4cb.png)

**Comment by mojina8** [comment]
我重新登录过，进入登录状态的 my 页面，要报401

**Comment by lipengzhou** [comment]
![image](https://user-images.githubusercontent.com/23165266/81762807-261a0700-9500-11ea-8374-95e2a20b371d.png)

**Comment by mojina8** [comment]
https://gitee.com/mojina6/toutiao-m

**Comment by lipengzhou** [comment]
代码位置：https://gitee.com/mojina6/toutiao-m/blob/master/src/views/login/index.vue#L106，应该写成：

```js
const { data } = await login(this.user)
```

如果你不这样写的话，那么你在使用数据时候就应该是：`data.data.data`。

**Comment by mojina8** [comment]
好的，已解决，谢谢老师
