### ISSUE TITLE
当token过期的时候,页面还停留在登录状态,里边的数据已经没有了如何解决?

### ISSUE THREAD

**Issue by ldd-bit** [lipengzhou/toutiao-mobile#21]
![image](https://user-images.githubusercontent.com/62420075/81723424-630cdc00-94b5-11ea-9483-2a8beef973d3.png)

**Comment by ldd-bit** [comment]
上边的图片传错了,!!!

**Comment by ldd-bit** [comment]
还有就是手动删除token页面不会自动跳转如何解决

**Comment by lipengzhou** [comment]
![](https://user-images.githubusercontent.com/23165266/81760253-53af8200-94f9-11ea-9150-cc40ba61e4cb.png)

**Comment by ldd-bit** [comment]
好的
