### ISSUE TITLE
数据一直在加载中不显示 , console报错

### ISSUE THREAD

**Issue by CapricornA** [lipengzhou/toutiao-mobile#23]
### 概述
- 打开首页, 一直提示在加载中, 在 console中疯狂报错
### 报错信息
```
[Vue warn]: Property or method "aritcle" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property.
```
```
[Vue warn]: Error in render: "TypeError: Cannot read property 'cover' of undefined"
```
```
TypeError: Cannot read property 'cover' of undefined
```
附上截图:
![image](https://user-images.githubusercontent.com/46157007/81788426-15d04f00-9535-11ea-9df0-ca799df41056.png)

### 你的代码
[我的仓库地址](https://github.com/CapricornA/toutiao-m)
最好是你的仓库地址并且确认你已把代码更新到线上。

**Comment by lipengzhou** [comment]
你在组件中访问了一个名字叫 `aritcle` 的数据不存在，正确的名字应该是 `article`。

![image](https://user-images.githubusercontent.com/23165266/81791648-909b6900-9539-11ea-8b77-f1a934a25886.png)

**Comment by CapricornA** [comment]
已经解决了, 谢谢老师 XD
