### ISSUE TITLE
插槽的api是在哪里看的?

### ISSUE THREAD

**Issue by qianshou99** [lipengzhou/toutiao-mobile#24]
### 概述
文章列表项的,slot="title"slot="label",为什么slot="label就是下面的角标呢?是在哪个组件看的?
### 你的代码

最好是你的仓库地址并且确认你已把代码更新到线上。

**Comment by ldd-bit** [comment]
在Cell单元格最下边有

**Comment by lipengzhou** [comment]
参考文档：https://youzan.github.io/vant/#/zh-CN/cell#cell-slots

**Comment by qianshou99** [comment]
已解决,感谢
