### ISSUE TITLE
下拉刷新时,鼠标下拉页面就会消失,不报错

### ISSUE THREAD

**Issue by vae-hehe** [lipengzhou/toutiao-mobile#25]
### 重现步骤
```js
<!-- 下拉刷新 -->
  <van-pull-refresh
    v-model="isRefreshLoading"
    @refresh="onRefresh"
  >
    <van-list
      class="list-wrap"
      v-model="loading"
      :finished="finished"
      finished-text="没有更多了"
      @load="onLoad"
    >
      <van-cell v-for="(article, index) in articles" :key="index" :title="article.title" />
    </van-list>
  </van-pull-refresh>

    onRefresh () {
      console.log(11)
    }
```
### 你的代码

最好是你的仓库地址并且确认你已把代码更新到线上。
https://gitee.com/vae11/toutiao-mobile

**Comment by beike-sun** [comment]
你试试
`  <van-list
      class="list-wrap"
      v-model="loading"
      :finished="finished"
      finished-text="没有更多了"
      @load="onLoad"
    >

  <van-pull-refresh
    v-model="isRefreshLoading"
    @refresh="onRefresh"
  >
 </van-pull-refresh>
 <van-cell v-for="(article, index) in articles" :key="index" :title="article.title" />
</van-list>
 `

**Comment by lipengzhou** [comment]
你的仓库是私有的，我没有权限查看。

**Comment by vae-hehe** [comment]
https://gitee.com/vae11/toutiao-mobile/commits/master 现在可以了

**Comment by lipengzhou** [comment]
应该把文章列表组件的根节点设置固定定位。

![image](https://user-images.githubusercontent.com/23165266/81913462-94df8900-9602-11ea-9761-5d602171fbe2.png)

具体可以这样修改：

![image](https://user-images.githubusercontent.com/23165266/81913500-a4f76880-9602-11ea-8ee1-79fb86942522.png)

**Comment by vae-hehe** [comment]
已解决, 谢谢老师
