### ISSUE TITLE
el-date-picker 选择限制到小时可选

### ISSUE THREAD

**Issue by li-erjun** [lipengzhou/toutiao-mobile#27]
el-date-picker  type 为  datetime 此时 可以选择 日期和 时间

如何 设置可以限定时间选择  只出现小时  或者出现分钟 但是分钟固定只显示00 

![image](https://user-images.githubusercontent.com/64782193/82024560-8d7fb480-96c2-11ea-8090-c991707f8cde.png)

**Comment by lipengzhou** [comment]
DateTimePicker 由 DatePicker 和 TimePicker 派生，Picker Options 或者其他选项可以参照 DatePicker 和 TimePicker。

你的需求可以在 [TimePicker 时间选择器](https://element.eleme.cn/#/zh-CN/component/time-picker) 中找到答案。
