### ISSUE TITLE
关于组件传值的疑惑

### ISSUE THREAD

**Issue by ldd-bit** [lipengzhou/toutiao-mobile#28]
老师,我有点不懂为什么channel(用户频道)在子组件里边直接修改,父组件就可以跟着变化,为什么active(被选中的频道),为什么就需要父组件传给子组件,子组件修改完传给父组件才生效

**Comment by lipengzhou** [comment]
> [官方文档](https://cn.vuejs.org/v2/guide/components-props.html#%E5%8D%95%E5%90%91%E6%95%B0%E6%8D%AE%E6%B5%81)解释：注意在 JavaScript 中对象和数组是通过引用传入的，所以对于一个数组或对象类型的 prop 来说，在子组件中改变变更这个对象或数组本身将会影响到父组件的状态。

props 数据如果是引用类型（对象、数组）可以修改它的内部数据，例如下面这样：

```js
obj.a = 123
arr.push(123)
```

但是要注意的是任何 props 数据都不能重新赋值：`xxx = xxx`，无论它是什么类型。

**Comment by ldd-bit** [comment]
好的,明白了,谢谢老师
