### ISSUE TITLE
修改完性别后刷新页面发现没改过来

### ISSUE THREAD

**Issue by yuanyuan-xy** [lipengzhou/toutiao-mobile#30]
### 概述
发送 将性别改成男 请求之后,页面改过来了,但是一刷新页面就又改成女了
### 重现步骤
发送的时候带参数了啊
![image](https://user-images.githubusercontent.com/62045686/82554768-25850e80-9b99-11ea-8831-83fd76e39261.png)

### 你的代码

最好是你的仓库地址并且确认你已把代码更新到线上。
github 仓库地址:`https://github.com/yuanyuan-xy/toutiao-mobile`

**Comment by lipengzhou** [comment]
已确认这是后台接口的一个 bug，和前端没有关系，所以暂时只把前端的交互做好即可。
