### ISSUE TITLE
报错：Error in v-on handler (Promise/async): "Error: Request failed with status code 400"

### ISSUE THREAD

**Issue by wanghuiru1238** [lipengzhou/toutiao-mobile#31]
### 概述
点击文章内容跳到文章详情页面时 会报错 ，同时也获取不到评论列表，
刷新页面 控制台报错就会消失 并且评论列表页加载出来了

### 报错信息
![image](https://user-images.githubusercontent.com/62423564/82732876-bb0fd200-9d42-11ea-873a-618274e59fbd.png)

### 你的代码
...js
export default {
  name: 'CommentList',
  components: {
    CommentItem
  },
  props: {
    source: {
      type: [Number, String, Object],
      required: true
    }
  },
  data () {
    return {
      comments: [],
      loading: false,
      finished: false,
      offset: null, // 获取下一页数据的页码
      limit: 10 // 每页大小
    }
  },
  computed: {},
  watch: {},
  created () {},
  mounted () {},
  methods: {
    async onLoad () {
      // 1.请求获取数据
      const { data } = await getComments({
        type: 'a', // 评论类型，a-对文章(article)的评论，c-对评论(comment)的回复
        source: this.source, // 源id，文章id或评论id
        offset: this.offset, // 获取评论数据的偏移量，值为评论id，表示从此id的数据向后取，不传表示从第一页开始读取数据
        limit: this.limit // 每页大小
      })
      // 2.将数据渲染到列表
      const { results } = data.data
      this.comments.push(...results)
      // 3.将本次loading关闭
      this.loading = false
      // 4判断是否还有数据
      if (results.length) {
        // 如果有，更新获取下一页数据的页码
        this.offset = data.data.last_id
      } else {
        // 如果没有，则将 finished 设置为 ture
        this.finished = true
      }
    }
  }
}
...
最好是你的仓库地址并且确认你已把代码更新到线上。

https://github.com/wanghuiru1238/toutiao-p.git

**Comment by lipengzhou** [comment]
错误位置：https://github.com/wanghuiru1238/toutiao-p/blob/master/src/views/article/components/comment-list.vue#L46

修改为：

```js
source: this.source.toString()
```
