### ISSUE TITLE
只要保存一下less里的文件就出现一个css文件,怎么解决?

### ISSUE THREAD

**Issue by qianshou99** [lipengzhou/toutiao-mobile#6]
![image](https://user-images.githubusercontent.com/62420203/81471324-f24e9100-9222-11ea-8c1f-1fb99d8b0134.png)

**Comment by lipengzhou** [comment]
这是因为你的编辑器安装了一个自动把 less 编译为 css 的插件，把这个插件禁用或者卸载就可以了。

你不知道你安装了哪个 less 编译插件是吧？看下图，在 VSC 扩展管理中找到名字中有 less 的插件，例如我这里有个名字叫 Easy  LESS（你可能是别的）的插件，把它禁用或者卸载即可。

![image](https://user-images.githubusercontent.com/23165266/81471632-114e2280-9225-11ea-8958-8e1d598c69ce.png)

![image](https://user-images.githubusercontent.com/23165266/81471670-45294800-9225-11ea-91c2-9748bc21172c.png)
