### ISSUE TITLE
字体图标不显示

### ISSUE THREAD

**Issue by fengge521** [lipengzhou/toutiao-mobile#7]
![image](https://user-images.githubusercontent.com/62426243/81471378-190cc780-9223-11ea-862a-0738a4220728.png)

**Comment by lipengzhou** [comment]
![image](https://user-images.githubusercontent.com/23165266/81471509-25455480-9224-11ea-86a3-efe7e7ebeadd.png)

要确保 Font Class 前缀和 Font Family 必须符合上面的规则，例如你可以是 `abc` 和 `abc-`，或者 `haha` 和 `haha-`。

如果不符合上述的规则，可以编辑项目重新修改：

![image](https://user-images.githubusercontent.com/23165266/81471562-8705be80-9224-11ea-823f-3ad9c9bc1b7c.png)
