### ISSUE TITLE
报错：TypeError: Object(...) is not a function

### ISSUE THREAD

**Issue by LLY546498** [lipengzhou/toutiao-mobile#8]
实在不知道到底是哪里出问题， 和老师的代码对比了半天 也没有对比出不一样的地方
![image](https://user-images.githubusercontent.com/62419972/81476882-ff7d7700-9246-11ea-86bd-6b9284ccb5a2.png)
`js
 methods: {
    async onLogin () {
      try {
        const res = await login(this.user)

        console.log(res)
      } catch (err) {
        console.log(err)
        console.log('登录失败', err)
      }
    }
  }`

`
import { request } from '@/utils/request'
// 登录注册
export const login = data => {
  return request({
    method: 'POST',
    url: '/app/v1_0/authorizations',
    data
  })
}
`

**Comment by lipengzhou** [comment]
加载 request 模块写错了，应该是这样的：

```js
import request from '@/utils/request'
```
