### ISSUE TITLE
编译问题

### ISSUE THREAD

**Issue by zhang-123A** [lipengzhou/toutiao-mobile#9]
![问题](https://user-images.githubusercontent.com/65053553/81478255-a285bf00-924e-11ea-8c48-3e90aca6d1ac.jpg)找了半天这个问题不知道怎么解决

**Comment by lipengzhou** [comment]
它的意思是说没有找到 `views/home.vue` 这个模块。

1. 检查该模块是否存在
2. 检查你写的加载路径是否正确
